### ISSUE TITLE
Determine if Cellimage module create an image if not all nodes exist.

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlas-app#69]
For example PCAWG doesn't have a Tumor fraction estimate. Can cellimage module make the cell image if that node does not exist?

**Comment by heimannch** [comment]
An underlying question is: do we want to display that the data is missing? In the example that PCAWG doesn't have Tumor fraction estimate, we could exclude this from the representation or determine a color for NA (like some sort of light gray).

**Comment by andrewelamb** [comment]
@heimannch If decide you don't want to do this we'll want to do something so that users don't get an error like it is now.

**Comment by heimannch** [comment]
The reason I brought up is question is because the course of action would be different - if we exclude the node from the visualization, it will be a matter of adjusting how to avoid it causing the error, whereas a different color for missing data would imply in changes, among others, to the style files. 
@vthorsson, do you have any thoughts on this (exclude node x different color for missing data)?

**Comment by vthorsson** [comment]
@heimannch  I think your suggestion of light gray for data NA makes sense (the illustration, for one, would look funny with no tumor cell) - hopefully it is not too hard to implement

**Comment by heimannch** [comment]
@vthorsson, for the illustration we'll need to include in the annotations an extra color for when a value is NA. For the network, adding this annotation is straightforward, but I think I will implement it after we find a way to code this for the illustration. 
Other than that, we would need to discuss with @andrewelamb  how to add this data (Tumor fraction NA in PCAWG) in this module.

**Comment by vthorsson** [comment]
@heimannch , agree that this would need some special handling, e.g. if value is NA then don't perform the mapping of value onto colorscale. 

 I did a bit of looking and it does seem like PCAWG generated tumor fraction / tumor purity. Since the above is a very specific issue arising with one cell in the cell illustration, I wonder if I our time would be better spent seeing if we can get the data in . (I have not yet seen a specific PCAWG file to work with , but tumor purity is used in the manuscripts)

**Comment by andrewelamb** [comment]
@vthorsson We could definitely add the PCAWG values for tumor fraction.

However we shoudl think about what we want to happen when we add new datasets in the future, and how we should handle cases where that dataset doesn't have data for one or more of the nodes.

**Comment by vthorsson** [comment]
Started branch `feature/cellimage_lacking_feature_data`. Missing values are now displayed in as gray `#e6e6e6` plus alpha received from annotations (which is usually 1.0).  Tried out darker gray (to better show tumor cell nucleus, e.g.) but it seemed too dark.

**Comment by vthorsson** [comment]
@heimannch are you able to explore modifying the legend color bar to indicate this color when value is missing?

**Comment by heimannch** [comment]
Sure! I made a first version of it with the label "Value not available" to avoid any confusion that may arise from using "missing data", but feel free to suggest any edits.
![cell-image-legend-full](https://user-images.githubusercontent.com/32350126/103687902-e21fba80-4f45-11eb-9915-3a5c1f0f520a.png)

**Comment by vthorsson** [comment]
Looks great @heimannch . Agree "Value not available"  is a good choice of text

**Comment by heimannch** [comment]
@vthorsson, @andrewelamb commit 16c74ca5a517bea461bf0f21c8840d829cbbf7c0 in branch `feature/cellimage_lacking_feature_data` includes the updated legend and network with nodes with missing data in gray.
